---
- name: Install Bash Completion
  apt: package=bash-completion state=present
  sudo: yes

- name: Turn On Color Prompt
  lineinfile:
    dest: /home/{{ console_user | default(ansible_user_id) }}/.bashrc
    line: "force_color_prompt=yes"
    regexp: '#?force_color_prompt=yes'
    state: present

- name: More User Friendly List Aliases
  lineinfile:
    dest: /home/{{ console_user | default(ansible_user_id) }}/.bashrc
    line: "alias {{ item.alias }}='{{ item.command }}'"
    regexp: "^alias {{ item.alias }}="
    state: present
  with_items:
    - { alias: ll, command: "ls -lFh" }
    - { alias: la, command: "ls -lFhA" }
    - { alias: l,  command: "ls -CF" }
