---
- name: Install Common Dev Tools
  apt: name={{ item }} state=present
  become: yes
  with_items:
    - git
    - vim
    - beanstalkd
    - supervisor
    - sed
  notify:
    - Restart Beanstalk
    - Restart Supervisor

- name: Install Bower, Gulp, & Grunt
  npm: name={{ item }} global=yes state=present
  become: yes
  with_items:
    - bower
    - gulp
    - grunt-cli

- name: Add Yarn APT Key
  apt_key: url=https://dl.yarnpkg.com/debian/pubkey.gpg state=present
  become: yes

- name: Add Yarn APT Repository
  apt_repository:
    repo: "deb https://dl.yarnpkg.com/debian/ stable main"
    state: present
  become: yes

- name: Install Yarn
  apt: name=yarn state=present
  become: yes

- name: Install SASS
  gem:
    name: sass
    user_install: no
    state: present
    executable: "{{ 'gem2.0' if ansible_distribution_release == 'trusty' else 'gem' }}"
    include_doc: "{{ env_name == 'dev' }}"
  become: yes

- name: Configure Vim
  copy:
    src: vimrc
    dest: /etc/vim/vimrc
    owner: root
    group: root
    mode: 0644
  become: yes
