---
- name: Install Git, Beanstalk, & Supervisor
  apt: name={{ item }} state=present
  become: yes
  with_items:
    - git
    - beanstalkd
    - supervisor

- name: Install Bower, Gulp, & Grunt
  npm: name={{ item }} global=yes state=present
  become: yes
  with_items:
    - bower
    - gulp
    - grunt-cli

- name: Install APT HTTPS Transport
  apt: name=apt-transport-https state=present
  become: yes

- name: Add Yarn APT Key
  apt_key: url=https://dl.yarnpkg.com/debian/pubkey.gpg state=present
  become: yes

- name: Add Yarn APT Repository
  apt_repository:
    repo: "deb https://dl.yarnpkg.com/debian/ stable main"
    state: present
  become: yes

- name: Install Yarn
  apt: name=yarn state=present
  become: yes

- name: Install SASS
  gem:
    name: sass
    user_install: no
    state: present
    executable: "{{ 'gem2.0' if ansible_distribution_release == 'trusty' else 'gem' }}"
    include_doc: "{{ env_name == 'trusty' }}"
  become: yes
