---
- name: Install Git, Beanstalk, & Supervisor
  apt: name={{ item }} state=present
  become: yes
  with_items:
    - git
    - beanstalkd
    - supervisor

- name: Install Bower, Gulp, & Grunt
  npm: name={{ item }} global=yes production=yes state=present
  become: yes
  with_items:
    - bower
    - gulp
    - grunt-cli

- name: Install SASS
  gem: name=sass user_install=no state=present
  become: yes
