---
- include: timezone.yml
- include: sysctl.yml
- include: system-updates.yml
- include: system-utilities.yml
- include: swap.yml
- include: redis.yml
- include: ruby.yml
- include: nodejs.yml
- include: dev-utils.yml
- include: bash-profile.yml
