---
- include_tasks: sysctl.yml
  tags: [sysctl]

- include_tasks: updates.yml
  tags: [apt]

- name: Configure Vim
  copy:
    src: vimrc
    dest: /etc/vim/vimrc
    owner: root
    group: root
    mode: 0644
  become: yes

- include_tasks: bash-profile.yml
  tags: [bash]

- include_tasks: acl.yml
  tags: [acl]
