---
- name: Install System Ruby
  apt: name={{ item }} state=present
  become: yes
  with_items:
    - '{{ "ruby2.0" if ansible_distribution_release == "trusty" else "ruby" }}'
    - '{{ "ruby2.0-dev" if ansible_distribution_release == "trusty" else "ruby-dev" }}'

- name: Set Gem Documentation Options
  lineinfile:
    dest: /etc/gemrc
    create: yes
    state: present
    line: "gem: {{ '--document rdoc,ri' if env_name == 'dev' else '--no-document' }}"
    regexp: "^gem:"
  become: yes

- name: Install FFI Development Headers
  apt: name=libffi-dev state=present
  become: yes
