---
- name: Install System Ruby
  apt: package={{ item }} state=present
  become: yes
  with_items:
    - ruby
    - ruby2.0

- name: Set Gem Documentation Options
  lineinfile:
    dest: /etc/gemrc
    create: yes
    state: present
    line: "gem: {{ '--no-rdoc --no-ri' if env_name != 'dev' else '' }}"
    regexp: "^gem:"
  become: yes
