---
- name: Install System Ruby
  apt: package={{ item }} state=present
  sudo: yes
  with_items:
    - ruby
    - ruby2.0

- name: Set Gem Documentation Options
  lineinfile:
    dest: /etc/gemrc
    create: yes
    state: present
    line: "gem: {{ '--no-rdoc --no-ri' if app_env != 'dev' else '' }}"
    regexp: "^gem:"
  sudo: yes
