---
- name: Install System Ruby
  apt: name={{ "ruby2.0" if ansible_distribution_release == "trusty" else "ruby" }} state=present
  become: yes

- name: Set Gem Documentation Options
  lineinfile:
    dest: /etc/gemrc
    create: yes
    state: present
    line: "gem: {{ '--document rdoc,ri' if env_name == 'dev' else '--no-document' }}"
    regexp: "^gem:"
  become: yes
