---
- name: Install System Ruby
  apt: package={{ item }} state=present
  sudo: yes
  with_items:
    - ruby
    - ruby2.0

- name: Skip Gem Documentation
  lineinfile:
    dest: /etc/gemrc
    create: yes
    state: present
    line: "gem: --no-rdoc --no-ri"
    regexp: "^gem:"
  sudo: yes
  when: app_env is defined and app_env != "dev"
