---
- name: Create Swap File
  command: fallocate -l 1G /swap
  become: yes
  when: ansible_swaptotal_mb < 1023

- name: Secure Swap File
  file: name=/swap owner=root group=root mode=0600
  become: yes

- name: Make Swap
  command: mkswap /swap
  become: yes
  when: ansible_swaptotal_mb < 1023
  notify: Turn on Swap

- name: Add Swap to Fstab
  lineinfile:
    dest:   /etc/fstab
    regexp: "swap"
    line:   "/swap none swap sw 0 0"
    state:  present
  become: yes
