---
- name: Install NTP Daemon
  apt: pkg=ntp state=present
  become: yes

- name: Remove ntpdate Package
  apt: pkg=ntpdate state=absent
  become: yes

- name: Check Current Timezone
  command: cat /etc/timezone
  register: current_timezone
  changed_when: no

- name: Set Timezone
  command: timedatectl set-timezone {{ timezone }}
  when: timezone != current_timezone.stdout
  become: yes
