---
# Required before we can update APT
- name: Install Aptitude
  apt: pkg=aptitude state=present
  become: yes

- name: Update APT
  apt: update_cache=yes upgrade=safe cache_valid_time=86400
  become: yes

- name: Install APT & Ubuntu Utils
  apt:
    name:
      - update-notifier-common
      - apt-transport-https
      - landscape-client
    state: present
  become: yes

- name: Configure Landscape Sysinfo
  copy:
    src: landscape.conf
    dest: /etc/landscape/client.conf
    owner: landscape
    group: root
    mode: 0600
  become: yes

- name: Remove Ubuntu Advantage from Motd
  file: name=/etc/update-motd.d/51-cloudguest state=absent
  become: yes
