---
# Considered deprecated some time after Xenial
- name: Update APT Keys
  script: update-apt-keys.pl
  become: yes
  register: apt_key_result
  changed_when: apt_key_result.stdout | int != 0

# Required before we can update APT
- name: Install Aptitude
  apt: pkg=aptitude state=present
  become: yes

- name: Update APT
  apt: update_cache=yes upgrade=safe cache_valid_time=86400
  become: yes

- name: Install Unattended Upgrades
  apt: pkg={{ item }} state=present
  become: yes
  with_items:
    - unattended-upgrades
    - update-notifier-common

- name: Install Landscape Client
  apt: pkg=landscape-client state=present
  become: yes

- name: Configure Landscape Sysinfo
  copy:
    src: landscape.conf
    dest: /etc/landscape/client.conf
    owner: landscape
    group: root
    mode: 0600
  become: yes

- name: Remove Ubuntu Advantage from Motd
  file: name=/etc/update-motd.d/51-cloudguest state=absent
  become: yes

- name: Configure Unattended Upgrades
  copy:
    src: 50unattended-upgrades
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    owner: root
    group: root
    mode: 0644
  become: yes

- name: Configure APT Periodic Settings
  lineinfile:
    dest: /etc/apt/apt.conf.d/10periodic
    line: '{{ item.key }} "{{ item.value }}";'
    regexp: "^{{ item.key }}"
    state: present
    create: yes
  with_items:
    - { key: "APT::Periodic::AutocleanInterval",    value: 7 }
    - { key: "APT::Periodic::Update-Package-Lists", value: 1 }
  become: yes

- name: Configure Unattended Upgrades
  lineinfile:
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    line: '{{ item.key }} "{{ item.value }}";'
    regexp: "^{{ item.key }}"
    state: present
    create: yes
  with_items:
    - { key: "APT::Periodic::Update-Package-Lists", value: 1 }
    - { key: "APT::Periodic::Unattended-Upgrade",   value: 1 }
  become: yes
