---
- name: Restart Redis
  service: name=redis-server state=restarted
  sudo: yes

- name: Update Timezone
  command: dpkg-reconfigure -f noninteractive tzdata
  sudo: yes

- name: Turn on Swap
  command: swapon -ae
  sudo: yes

- name: Restart Procps
  service: name=procps state=restarted
  sudo: yes
