---
- name: Restart Procps
  service: name=procps state=restarted
  become: yes
  when: ansible_connection | default('smart') != 'docker'

- name: Remount Root
  command: mount -o remount / warn=no
  become: yes
  when: ansible_connection | default('smart') != 'docker'
