---
- hosts: all

  tasks:
    - include: ../../tasks/acl.yml

  post_tasks:
    - name: Create Test Directory
      file: path={{ ansible_user_dir }}/acl_test state=directory owner=root group=root
      become: true

  handlers:
    - include: ../../handlers/main.yml
