---
- hosts: all
  become: yes

  vars:
    - console_user: test_user

  pre_tasks:
    - name: Create test user for spec
      user:
        name:     "{{ console_user }}"
        password: ""
        shell:    /bin/bash
        state:    present

  post_tasks:
    - name: Create Mocks Directory
      file:
        name: /tmp/mocks
        state: directory
        mode: 0777
    - name: Mock regular file for spec
      command: dd if=/dev/zero of=/tmp/mocks/test bs=1024 count=1
    - name: Mock hidden file for spec
      command: dd if=/dev/zero of=/tmp/mocks/.test bs=1024 count=1024
    - name: Set permissions for mock file
      file:
        name: /tmp/mocks/test
        mode: 0644
        owner: root
        group: root
        state: file
    - name: Set permissions for hidden file
      file:
        name: /tmp/mocks/.test
        mode: 0755
        owner: root
        group: root
        state: file

  tasks:
    - include: ../../tasks/bash-profile.yml
