---
- hosts: all
  tasks:
    - include: ../../tasks/bash-profile.yml
    - command: dd if=/dev/zero of={{ ansible_user_dir }}/test bs=1024 count=1
    - command: dd if=/dev/zero of={{ ansible_user_dir }}/.test bs=1024 count=1024
    - file: name={{ ansible_user_dir }}/test mode=0644 state=file
    - file: name={{ ansible_user_dir }}/.test mode=0755 state=file
    - file: name={{ ansible_user_dir }}/test_dir mode=0755 state=directory
