---
- hosts: all

  post_tasks:
    - name: Create Mocks Directory
      file:
        name: /tmp/mocks
        state: directory
        mode: 0777
    - name: Mock regular file for spec
      command: dd if=/dev/zero of=/tmp/mocks/test bs=1024 count=1
      become: yes
    - name: Mock hidden file for spec
      command: dd if=/dev/zero of=/tmp/mocks/.test bs=1024 count=1024
      become: yes
    - name: Set permissions for mock file
      file:
        name: /tmp/mocks/test
        mode: 0644
        owner: root
        group: root
        state: file
      become: yes
    - name: Set permissions for hidden file
      file:
        name: /tmp/mocks/.test
        mode: 0755
        owner: root
        group: root
        state: file
      become: yes

  tasks:
    - include: ../../tasks/bash-profile.yml
