---
- hosts: all
  vars_files:
    - ../../defaults/main.yml
  tasks:
    # Include task to update APT cache before doing other installs
    - include: ../../tasks/updates.yml

    # Required tasks for installing dev tools
    - include: ../../tasks/nodejs.yml
    - include: ../../tasks/ruby.yml

    - include: ../../tasks/dev-tools.yml
