---
- hosts: all
  vars_files:
    - ../../defaults/main.yml
  tasks:
    # Include task to update APT cache before doing other installs
    - include: ../../tasks/updates.yml

    - include: ../../tasks/ruby.yml
